### PR TITLE
add search in browse-apis; upgrade devDependencies; minor fixes

### PR DESCRIPTION
**Pull request by azbarcea**

### CODE REVIEW

**Comment by RomanGotsiy** [comment]
Hey @azbarcea, your code looks great!
There are only a few cosmetic things we would like to change: 
- make search input centered and text not bold like on the screenshot bellow:
- do search not on change but on keyup event to make it more interactive (if it gets laggy maybe throttle it a bit)

image

This are the only issues we need to resolve before merge your awesome PR :)

**Comment by azbarcea** [comment]
I have addressed your requests :-).

**Comment by IvanGoncharov** [comment]
Hi @azbarcea,

Thank you for your PR.
It very useful feature since we have more than 250 APIs in collection 👍 
In case if you want to help more, I reported issues that we want to implement in future:
https://github.com/APIs-guru/APIs-guru.github.io/issues

**Comment by azbarcea** [comment]
Was my pleasure.

I'll try and submit more PRs when I will have more time.

Have a nice day,
Alex

**Pull request merged**
